//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Error.proto
namespace ErrorCode
{
    [global::ProtoBuf.ProtoContract(Name=@"Code")]
    public enum Code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_NONE", Value=0)]
      ERR_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_VERSION_INVALID", Value=1)]
      ERR_VERSION_INVALID = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PLAYER_INVALID", Value=1000)]
      ERR_PLAYER_INVALID = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PLAYER_INVALID_ID", Value=1001)]
      ERR_PLAYER_INVALID_ID = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PLAYER_INVALID_GUID", Value=1002)]
      ERR_PLAYER_INVALID_GUID = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PLAYER_FLAGS_NOT_NONE", Value=1003)]
      ERR_PLAYER_FLAGS_NOT_NONE = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PLAYER_FLAGS_NOT_LOGIN", Value=1004)]
      ERR_PLAYER_FLAGS_NOT_LOGIN = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PLAYER_FLAGS_NOT_INGAME", Value=1005)]
      ERR_PLAYER_FLAGS_NOT_INGAME = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_PLAYER_FLAGS_INGAME", Value=1006)]
      ERR_PLAYER_FLAGS_INGAME = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_INVALID", Value=2000)]
      ERR_GAME_INVALID = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_INVALID_ID", Value=2001)]
      ERR_GAME_INVALID_ID = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_USING", Value=2002)]
      ERR_GAME_USING = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_EMPTY", Value=2003)]
      ERR_GAME_EMPTY = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_FULL", Value=2004)]
      ERR_GAME_FULL = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAME_PASSWORD", Value=2005)]
      ERR_GAME_PASSWORD = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SERVER_FULL", Value=3000)]
      ERR_SERVER_FULL = 3000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_GAMEPLAY_INVALID_MODE", Value=4000)]
      ERR_GAMEPLAY_INVALID_MODE = 4000
    }
  
}