//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameServerVersion.proto
namespace GameServerVersion
{
    [global::ProtoBuf.ProtoContract(Name=@"Code")]
    public enum Code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"VERSION", Value=65536)]
      VERSION = 65536
    }
  
}