//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Flags.proto
namespace FlagsCode
{
    [global::ProtoBuf.ProtoContract(Name=@"Code")]
    public enum Code
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_FLAGS_NONE", Value=0)]
      PLAYER_FLAGS_NONE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_FLAGS_LOGIN", Value=1)]
      PLAYER_FLAGS_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_FLAGS_WAITING", Value=2)]
      PLAYER_FLAGS_WAITING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_FLAGS_READY", Value=4)]
      PLAYER_FLAGS_READY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PLAYER_FLAGS_GAMING", Value=8)]
      PLAYER_FLAGS_GAMING = 8
    }
  
}