// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Flags.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Flags.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace FlagsCode {

namespace {

const ::google::protobuf::EnumDescriptor* Code_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Flags_2eproto() {
  protobuf_AddDesc_Flags_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Flags.proto");
  GOOGLE_CHECK(file != NULL);
  Code_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Flags_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_Flags_2eproto() {
}

void protobuf_AddDesc_Flags_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013Flags.proto\022\tFlagsCode*\265\001\n\004Code\022\025\n\021PLA"
    "YER_FLAGS_NONE\020\000\022\026\n\022PLAYER_FLAGS_LOGIN\020\001"
    "\022\030\n\024PLAYER_FLAGS_WAITING\020\002\022\026\n\022PLAYER_FLA"
    "GS_READY\020\004\022\027\n\023PLAYER_FLAGS_GAMING\020\010\022\027\n\021P"
    "LAYER_FLAGS_DEAD\020\200\200\004\022\032\n\024PLAYER_FLAGS_RES"
    "PAWN\020\200\200\010B\002H\001", 212);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Flags.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Flags_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Flags_2eproto {
  StaticDescriptorInitializer_Flags_2eproto() {
    protobuf_AddDesc_Flags_2eproto();
  }
} static_descriptor_initializer_Flags_2eproto_;
const ::google::protobuf::EnumDescriptor* Code_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Code_descriptor_;
}
bool Code_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 8:
    case 65536:
    case 131072:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace FlagsCode

// @@protoc_insertion_point(global_scope)
